//! The run-time variable scope (PRD §4/§10).
//!
//! Precedence (lowest → highest): WCL declaration → gatherer result →
//! `--var-file` → `--var`. Declared variables keep their original
//! expression text and are spliced into a generated `<weave/vars.wcl>`
//! system import as `let` declarations, so cross-references between
//! variables and gatherer results resolve through normal WCL scoping.
//! Stored values (gatherer results and overrides) are served through an
//! `Environment` builtin (`__weave_var`) so any value shape round-trips
//! without literal serialization.

use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;

use wcl_lang::{Document, Environment, Value, from_fn};

use crate::diag::Diag;
use crate::model::Playbook;
use crate::vocab;

/// Where a stored value came from; higher wins.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Origin {
    Gatherer = 1,
    VarFile = 2,
    Var = 3,
}

#[derive(Default, Clone)]
pub struct VarStore {
    vals: HashMap<String, (Origin, Value)>,
}

impl VarStore {
    pub fn new() -> VarStore {
        VarStore::default()
    }

    /// Insert respecting precedence: an existing higher-priority value
    /// wins over the incoming one.
    pub fn insert(&mut self, name: &str, origin: Origin, value: Value) {
        match self.vals.get(name) {
            Some((existing, _)) if *existing > origin => {}
            _ => {
                self.vals.insert(name.to_string(), (origin, value));
            }
        }
    }

    pub fn contains(&self, name: &str) -> bool {
        self.vals.contains_key(name)
    }

    /// Generate the `<weave/vars.wcl>` source for this store plus the
    /// playbook's declared variables (declared ones only where no stored
    /// value shadows them).
    pub fn vars_source(&self, pb: &Playbook) -> String {
        let mut out = String::new();
        out.push_str("// generated by config-weave; do not edit\n");
        let mut names: Vec<&String> = self.vals.keys().collect();
        names.sort();
        for name in names {
            out.push_str(&format!("let {name} = __weave_var(\"{name}\")\n"));
        }
        for var in &pb.vars {
            if !self.contains(&var.name) {
                out.push_str(&format!("let {} = {}\n", var.name, var.expr_src));
            }
        }
        out
    }

    /// Environment with the `__weave_var` builtin serving stored values.
    pub fn environment(&self) -> Environment {
        let store: Arc<HashMap<String, Value>> = Arc::new(
            self.vals
                .iter()
                .map(|(k, (_, v))| (k.clone(), v.clone()))
                .collect(),
        );
        let mut env = Environment::new();
        env.add_builtin(
            "__weave_var",
            from_fn(move |name: String| -> Result<Value, String> {
                store
                    .get(&name)
                    .cloned()
                    .ok_or_else(|| format!("no stored variable '{name}'"))
            }),
        );
        env
    }

    /// Open the playbook document with this variable scope bound.
    pub fn open_playbook(&self, pb: &Playbook) -> Result<Document, Diag> {
        let source = vocab::with_import(&pb.source, vocab::PLAYBOOK_IMPORT, true);
        let env = self.environment();
        Document::open_at_with_loader(
            &source,
            "playbook.wcl",
            Some(pb.root.clone()),
            &env,
            vocab::loader(Some(self.vars_source(pb))),
        )
        .map_err(Diag::from_parse)
    }
}

/// Parse a `--var KEY=VALUE` override. The value is parsed as a WCL
/// expression when possible (so `--var count=3` is an int and
/// `--var debug=true` a bool); anything that doesn't parse or evaluate
/// standalone is taken as a plain string.
pub fn parse_var_flag(flag: &str) -> Result<(String, Value), Diag> {
    let Some((key, raw)) = flag.split_once('=') else {
        return Err(Diag::bare(format!("--var expects KEY=VALUE, got '{flag}'")));
    };
    let key = key.trim();
    if !is_identifier(key) {
        return Err(Diag::bare(format!(
            "--var key '{key}' is not a valid identifier"
        )));
    }
    Ok((key.to_string(), parse_value(raw)))
}

fn parse_value(raw: &str) -> Value {
    if let Ok(expr) = wcl_lang::parse_expr(raw, "<--var>")
        && let Ok(doc) = Document::open("", "<--var>")
        && let Ok(v) = doc.eval_expr(&expr)
    {
        return v;
    }
    Value::Utf8(raw.to_string())
}

/// Read a `--var-file`: every top-level field becomes an override.
/// The file is parsed directly (no document schema applies) and each
/// field's expression evaluates standalone, so var files are flat
/// `name = value` collections.
pub fn load_var_file(path: &Path) -> Result<Vec<(String, Value)>, Vec<Diag>> {
    let source = std::fs::read_to_string(path)
        .map_err(|e| vec![Diag::bare(format!("cannot read {}: {e}", path.display()))])?;
    let parsed = wcl_lang::parse_for_edit(&source, path.display().to_string())
        .map_err(|e| vec![Diag::from_parse(e)])?;
    let scratch = Document::open("", "<var-file>").map_err(|e| vec![Diag::from_parse(e)])?;

    let mut out = Vec::new();
    let mut diags = Vec::new();
    for item in &parsed.items {
        if let wcl_lang::ast::Item::Field(f) = item {
            if !is_identifier(&f.name) {
                diags.push(Diag::bare(format!(
                    "{}: variable '{}' is not a valid identifier",
                    path.display(),
                    f.name
                )));
                continue;
            }
            match scratch.eval_expr(&f.expr) {
                Ok(v) => out.push((f.name.clone(), v)),
                Err(e) => diags.push(Diag::from_eval(e, path, &source)),
            }
        }
    }
    if diags.is_empty() {
        Ok(out)
    } else {
        Err(diags)
    }
}

pub fn is_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}
