//! The run-time variable scope (PRD §4/§10).
//!
//! Precedence (lowest → highest): WCL declaration → gatherer result →
//! `--var-file` → `--var`. Declared variables keep their original
//! expression text and are spliced into a generated `<weave/vars.wcl>`
//! system import as `let` declarations, so cross-references between
//! variables and gatherer results resolve through normal WCL scoping.
//! Stored values (gatherer results and overrides) are served through an
//! `Environment` builtin (`__weave_var`) so any value shape round-trips
//! without literal serialization.

use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;

use wcl_lang::{Document, Environment, Value, from_fn};

use crate::diag::Diag;
use crate::model::Playbook;
use crate::vocab;

/// Store key holding the whole argument map of a composite invocation.
/// Not a legal parameter name, so it cannot collide with an argument of
/// its own; the body sees it under [`ARGS_BINDING`].
const ARGS_MAP: &str = "__weave_args";

/// What a composite body calls the map of the arguments it was invoked
/// with. Declarations are singular (`arg "path" { … }`) and the map is
/// plural, which is also what keeps them from colliding: WCL puts a
/// block's own kinds and schema fields in scope, so a map named after
/// either would read the declarations instead of the values.
pub const ARGS_BINDING: &str = "args";

/// Where a stored value came from; higher wins.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Origin {
    Gatherer = 1,
    VarFile = 2,
    Var = 3,
}

#[derive(Default, Clone)]
pub struct VarStore {
    vals: HashMap<String, (Origin, Value)>,
    /// Present once a password has been resolved; makes `secret("…")`
    /// decrypt rather than evaluate to the locked placeholder.
    secrets: Option<Arc<crate::secrets::SecretCtx>>,
}

impl VarStore {
    pub fn new() -> VarStore {
        VarStore::default()
    }

    /// Bind a decryption context, so `secret()` resolves for real in
    /// every document this store opens.
    pub fn with_secrets(mut self, ctx: Arc<crate::secrets::SecretCtx>) -> VarStore {
        self.secrets = Some(ctx);
        self
    }

    /// Insert respecting precedence: an existing higher-priority value
    /// wins over the incoming one.
    pub fn insert(&mut self, name: &str, origin: Origin, value: Value) {
        match self.vals.get(name) {
            Some((existing, _)) if *existing > origin => {}
            _ => {
                self.vals.insert(name.to_string(), (origin, value));
            }
        }
    }

    pub fn contains(&self, name: &str) -> bool {
        self.vals.contains_key(name)
    }

    /// Generate the `<weave/vars.wcl>` source for this store plus the
    /// playbook's declared variables (declared ones only where no stored
    /// value shadows them).
    pub fn vars_source(&self, pb: &Playbook) -> String {
        let mut out = String::new();
        out.push_str("// generated by config-weave; do not edit\n");
        let mut names: Vec<&String> = self.vals.keys().collect();
        names.sort();
        for name in names {
            out.push_str(&format!("let {name} = __weave_var(\"{name}\")\n"));
        }
        for var in &pb.vars {
            if !self.contains(&var.name) {
                out.push_str(&format!("let {} = {}\n", var.name, var.expr_src));
            }
        }
        out
    }

    /// Environment with the `__weave_var` builtin serving stored values,
    /// plus `secret()` — decrypting when a password has been bound,
    /// otherwise the locked placeholder.
    pub fn environment(&self) -> Environment {
        let store: Arc<HashMap<String, Value>> = Arc::new(
            self.vals
                .iter()
                .map(|(k, (_, v))| (k.clone(), v.clone()))
                .collect(),
        );
        let mut env = Environment::new();
        env.add_builtin(
            "__weave_var",
            from_fn(move |name: String| -> Result<Value, String> {
                store
                    .get(&name)
                    .cloned()
                    .ok_or_else(|| format!("no stored variable '{name}'"))
            }),
        );
        crate::secrets::env::register(&mut env, self.secrets.clone());
        env
    }

    /// Open the document declaring a composite, with one invocation's
    /// arguments bound as its whole variable scope.
    ///
    /// A composite body sees *only* its own arguments — not gatherer
    /// results, declared vars or `--var` overrides — so this deliberately
    /// starts from an empty store rather than `self`. Each binds twice:
    /// bare (`body`) and under an `args` map (`args.body`). Prefer the
    /// latter, because a property field shadows a bare outer variable of
    /// the same name and `path = path` would be a self-reference.
    pub fn open_composite(
        &self,
        source: &str,
        filename: &str,
        root: &Path,
        import: &str,
        args: &HashMap<String, Value>,
    ) -> Result<Document, Diag> {
        let mut scope = VarStore {
            vals: HashMap::new(),
            secrets: self.secrets.clone(),
        };
        for (k, v) in args {
            scope.insert(k, Origin::Gatherer, v.clone());
        }
        // Maps are anonymous records in WCL, so `args.body` is ordinary
        // member access.
        scope.insert(
            ARGS_MAP,
            Origin::Gatherer,
            Value::Record {
                ty: Vec::new(),
                fields: Arc::new(args.iter().map(|(k, v)| (k.clone(), v.clone())).collect()),
            },
        );

        let with_import = vocab::with_import(source, import, true);
        let mut vars = String::from("// generated by config-weave; do not edit\n");
        let mut names: Vec<&String> = scope.vals.keys().collect();
        names.sort();
        for name in names {
            let binding = if name == ARGS_MAP { ARGS_BINDING } else { name };
            vars.push_str(&format!("let {binding} = __weave_var(\"{name}\")\n"));
        }
        Document::open_at_with_loader(
            &with_import,
            filename,
            Some(root.to_path_buf()),
            &scope.environment(),
            vocab::loader(Some(vars)),
        )
        .map_err(Diag::from_parse)
    }

    /// Open the playbook document with this variable scope bound.
    pub fn open_playbook(&self, pb: &Playbook) -> Result<Document, Diag> {
        let source = vocab::with_import(&pb.source, vocab::PLAYBOOK_IMPORT, true);
        let env = self.environment();
        Document::open_at_with_loader(
            &source,
            "playbook.wcl",
            Some(pb.root.clone()),
            &env,
            vocab::loader(Some(self.vars_source(pb))),
        )
        .map_err(Diag::from_parse)
    }
}

/// Parse a `--var KEY=VALUE` override. The value is parsed as a WCL
/// expression when possible (so `--var count=3` is an int and
/// `--var debug=true` a bool); anything that doesn't parse or evaluate
/// standalone is taken as a plain string.
pub fn parse_var_flag(flag: &str) -> Result<(String, Value), Diag> {
    let Some((key, raw)) = flag.split_once('=') else {
        return Err(Diag::bare(format!("--var expects KEY=VALUE, got '{flag}'")));
    };
    let key = key.trim();
    if !is_identifier(key) {
        return Err(Diag::bare(format!(
            "--var key '{key}' is not a valid identifier"
        )));
    }
    Ok((key.to_string(), parse_value(raw)))
}

fn parse_value(raw: &str) -> Value {
    if let Ok(expr) = wcl_lang::parse_expr(raw, "<--var>")
        && let Ok(doc) = Document::open("", "<--var>")
        && let Ok(v) = doc.eval_expr(&expr)
    {
        return v;
    }
    Value::Utf8(raw.to_string())
}

/// Read a `--var-file`: every top-level field becomes an override.
/// The file is parsed directly (no document schema applies) and each
/// field's expression evaluates standalone, so var files are flat
/// `name = value` collections.
pub fn load_var_file(path: &Path) -> Result<Vec<(String, Value)>, Vec<Diag>> {
    let source = std::fs::read_to_string(path)
        .map_err(|e| vec![Diag::bare(format!("cannot read {}: {e}", path.display()))])?;
    let parsed = wcl_lang::parse_for_edit(&source, path.display().to_string())
        .map_err(|e| vec![Diag::from_parse(e)])?;
    let scratch = Document::open("", "<var-file>").map_err(|e| vec![Diag::from_parse(e)])?;

    let mut out = Vec::new();
    let mut diags = Vec::new();
    for item in &parsed.items {
        if let wcl_lang::ast::Item::Field(f) = item {
            if !is_identifier(&f.name) {
                diags.push(Diag::bare(format!(
                    "{}: variable '{}' is not a valid identifier",
                    path.display(),
                    f.name
                )));
                continue;
            }
            match scratch.eval_expr(&f.expr) {
                Ok(v) => out.push((f.name.clone(), v)),
                Err(e) => diags.push(Diag::from_eval(e, path, &source)),
            }
        }
    }
    if diags.is_empty() {
        Ok(out)
    } else {
        Err(diags)
    }
}

pub fn is_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}
